#!/usr/bin/env bash
#
# Ruko device capability probe.
#
# Collects the facts docs/android-capabilities.md depends on, straight from a
# connected device. Read-only: it installs nothing and changes no setting.
#
#   ./scripts/probe-device.sh                 # writes docs/device-report.md
#   ./scripts/probe-device.sh -s <serial>     # when several devices are attached
#
# Every "UNVERIFIED" marker in docs/android-capabilities.md is resolved by
# running this against the physical iQOO 15.

set -uo pipefail

ADB_SERIAL=""
while getopts "s:" opt; do
  case "$opt" in
    s) ADB_SERIAL="-s $OPTARG" ;;
    *) echo "usage: $0 [-s serial]" >&2; exit 2 ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/docs/device-report.md"

if ! command -v adb >/dev/null 2>&1; then
  echo "adb not found on PATH. Install platform-tools first." >&2
  exit 1
fi

# shellcheck disable=SC2086
if [ -z "$(adb $ADB_SERIAL get-state 2>/dev/null)" ]; then
  echo "No device reachable. Connect the iQOO 15, enable USB debugging, and" >&2
  echo "accept the RSA prompt. 'adb devices -l' should list it as 'device'." >&2
  exit 1
fi

# shellcheck disable=SC2086
sh_() { adb $ADB_SERIAL shell "$@" 2>/dev/null | tr -d '\r'; }
prop() { sh_ getprop "$1"; }

section() { printf '\n## %s\n\n' "$1" >>"$OUT"; }
kv()      { printf '| %s | `%s` |\n' "$1" "${2:-<empty>}" >>"$OUT"; }
tablehead(){ printf '| Property | Value |\n| --- | --- |\n' >>"$OUT"; }
note()    { printf '\n%s\n' "$1" >>"$OUT"; }
fence()   { printf '\n```\n%s\n```\n' "$1" >>"$OUT"; }

# --- verdict helper: prints YES/NO plus the evidence it used -----------------
verdict() { # name, condition-output, yes-text, no-text
  if [ -n "$2" ]; then printf '| %s | **YES** | %s |\n' "$1" "$3" >>"$OUT"
  else                 printf '| %s | **NO** | %s |\n'  "$1" "$4" >>"$OUT"; fi
}

: >"$OUT"
{
  echo "# Ruko device capability report"
  echo
  echo "Generated by \`scripts/probe-device.sh\` on $(date -u '+%Y-%m-%dT%H:%M:%SZ')."
  echo "Read-only probe. Every value below was read from the device, not assumed."
} >>"$OUT"

# ---------------------------------------------------------------- identity --
section "Device identity"
tablehead
kv "Manufacturer"      "$(prop ro.product.manufacturer)"
kv "Brand"             "$(prop ro.product.brand)"
kv "Model"             "$(prop ro.product.model)"
kv "Device"            "$(prop ro.product.device)"
kv "Android release"   "$(prop ro.build.version.release)"
kv "SDK level"         "$(prop ro.build.version.sdk)"
kv "Security patch"    "$(prop ro.build.version.security_patch)"
kv "Build fingerprint" "$(prop ro.build.fingerprint)"
kv "OS skin version"   "$(prop ro.vivo.os.version)$(prop ro.vivo.os.name)"
kv "Primary ABI"       "$(prop ro.product.cpu.abi)"
kv "Supported ABIs"    "$(prop ro.product.cpu.abilist)"

# --------------------------------------------------------------------- SoC --
section "SoC and AI acceleration"
tablehead
kv "SoC manufacturer" "$(prop ro.soc.manufacturer)"
kv "SoC model"        "$(prop ro.soc.model)"
kv "Hardware"         "$(prop ro.hardware)"
kv "Board platform"   "$(prop ro.board.platform)"
kv "Vulkan level"     "$(prop ro.hardware.vulkan)"

note "### Qualcomm QNN / Hexagon libraries present on device"
note "These are what ONNX Runtime's QNN execution provider and the Qualcomm AI"
note "Engine Direct SDK link against. If \`libQnnHtp.so\` is absent, the NPU is"
note "**not** reachable by a normal app and Ruko must report \`CPU\` or \`NNAPI\`."
QNN_LIBS="$(sh_ 'ls /vendor/lib64/ /vendor/lib64/rfsa/adsp/ /system/lib64/ 2>/dev/null | grep -i -E "qnn|hexagon|htp|dsp" | sort -u')"
fence "${QNN_LIBS:-<none found>}"

note "### NNAPI / neural network HAL"
NNAPI_HAL="$(sh_ 'ls /vendor/lib64/hw/ 2>/dev/null | grep -i neural'; sh_ 'dumpsys package | grep -i -m5 neuralnetworks')"
fence "${NNAPI_HAL:-<none found>}"

note "### Capability verdicts"
printf '\n| Capability | Available | Evidence |\n| --- | --- | --- |\n' >>"$OUT"
verdict "Qualcomm HTP (NPU) libraries" \
        "$(echo "$QNN_LIBS" | grep -i htp)" \
        "libQnnHtp present in vendor libs" \
        "no libQnnHtp.so — NPU not reachable via QNN from an app process"
verdict "cDSP remote proc (libcdsprpc)" \
        "$(sh_ 'ls /vendor/lib64/libcdsprpc.so 2>/dev/null')" \
        "libcdsprpc.so present" \
        "absent — DSP offload unavailable"
verdict "NNAPI vendor driver" \
        "$NNAPI_HAL" \
        "a neuralnetworks HAL is registered" \
        "no vendor NNAPI driver visible; NNAPI would fall back to CPU reference"

note "> NNAPI is deprecated from Android 15 (API 35) onward. Confirm the SDK"
note "> level above before planning on it as the primary accelerated path."

# ------------------------------------------------------------------- audio --
section "Audio capture"
tablehead
kv "Low-latency audio"  "$(sh_ 'pm list features | grep -c audio.low_latency')"
kv "Pro audio"          "$(sh_ 'pm list features | grep -c audio.pro')"
kv "Microphone feature" "$(sh_ 'pm list features | grep -c hardware.microphone')"

note "### Speech recognition services installed"
SPEECH="$(sh_ 'pm list packages | grep -i -E "speech|tts|recognition"')"
fence "${SPEECH:-<none found>}"

note "### Audio sources"
note "Ruko uses \`MediaRecorder.AudioSource.VOICE_RECOGNITION\` on the device"
note "microphone. \`VOICE_CALL\`, \`VOICE_DOWNLINK\` and \`VOICE_UPLINK\` are"
note "privileged and are **not** available to a normal app — Ruko does not use"
note "them and must not claim to capture the call stream."

# ------------------------------------------------------- services / perms  --
section "Services Ruko depends on"

note "### Accessibility"
ACC_ENABLED="$(sh_ 'settings get secure enabled_accessibility_services')"
tablehead
kv "Enabled accessibility services" "$ACC_ENABLED"
kv "Accessibility master switch"    "$(sh_ 'settings get secure accessibility_enabled')"

note "### Notification listeners"
NL="$(sh_ 'settings get secure enabled_notification_listeners')"
tablehead
kv "Enabled notification listeners" "$NL"

note "### Ruko package state (empty until the app is installed)"
RUKO_PKG="$(sh_ 'pm list packages | grep -i ruko')"
fence "${RUKO_PKG:-<Ruko not installed>}"
if [ -n "$RUKO_PKG" ]; then
  note "#### Granted runtime permissions"
  fence "$(sh_ 'dumpsys package com.ruko | sed -n "/runtime permissions:/,/^$/p"')"
  note "#### Battery optimisation / background restriction"
  fence "$(sh_ 'dumpsys deviceidle whitelist | grep -i ruko'; sh_ 'appops get com.ruko RUN_IN_BACKGROUND')"
fi

# ------------------------------------------------------------ OEM behaviour --
section "OEM background policy (vivo / iQOO)"
note "iQOO ships OriginOS/Funtouch, which historically kills background services"
note "aggressively. These values tell us whether a foreground service will survive."
tablehead
kv "Power saving mode"     "$(sh_ 'settings get global low_power')"
kv "Adaptive battery"      "$(sh_ 'settings get global adaptive_battery_management_enabled')"
kv "App standby enabled"   "$(sh_ 'settings get global app_standby_enabled')"
kv "Doze whitelist count"  "$(sh_ 'dumpsys deviceidle whitelist | wc -l')"
VIVO_PKGS="$(sh_ 'pm list packages | grep -i -E "vivo.*(power|abe|smartshot|permission)"')"
note "vivo power/permission managers present:"
fence "${VIVO_PKGS:-<none found>}"

# ------------------------------------------------------------------ summary --
section "What this means for Ruko"
note "Fill the corresponding UNVERIFIED rows in \`docs/android-capabilities.md\`"
note "from the verdict tables above. Do not mark a backend as available in the"
note "Engineering screen unless a real inference ran on it and reported a latency."

echo "Wrote $OUT"
