/**
 * The TypeScript tokenizer must agree with the Python one that trained the
 * model, token for token. A tokenizer that disagrees produces a model that
 * appears to work and is quietly wrong — the worst possible failure for this
 * product, because nothing crashes.
 *
 * Reference ids in tokenizer_reference.json are generated by the real
 * HuggingFace tokenizer (see ml/export). Regenerate them if the vocab changes.
 */

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';

import { WordPieceTokenizer } from '../tokenizer.ts';

const VOCAB_PATH = 'ml/models/ruko-manip-v1/onnx/vocab.txt';
const REFERENCE_PATH = 'mobile/src/risk/classifier/__tests__/tokenizer_reference.json';

const hasArtifacts = existsSync(VOCAB_PATH) && existsSync(REFERENCE_PATH);

describe('WordPiece tokenizer', { skip: hasArtifacts ? false : 'run ml/export/export_onnx.py first' }, () => {
  const tokenizer = WordPieceTokenizer.fromVocabText(readFileSync(VOCAB_PATH, 'utf8'));
  const reference: Array<{ text: string; input_ids: number[]; tokens: string[] }> =
    JSON.parse(readFileSync(REFERENCE_PATH, 'utf8'));

  test('loads the exported vocabulary', () => {
    assert.equal(tokenizer.vocabSize, 30522);
  });

  for (const ref of reference) {
    const label = ref.text.trim() === '' ? '(empty/whitespace)' : ref.text.slice(0, 46);
    test(`matches HuggingFace exactly: ${label}`, () => {
      const enc = tokenizer.encode(ref.text);
      assert.deepEqual(enc.tokens, ref.tokens,
        `token mismatch\n  ours: ${enc.tokens.join(' ')}\n  ref:  ${ref.tokens.join(' ')}`);
      assert.deepEqual(enc.inputIds, ref.input_ids);
    });
  }

  test('padding fills to max length and masks the padding', () => {
    const enc = tokenizer.encode('hello sir', true);
    assert.equal(enc.inputIds.length, 64);
    assert.equal(enc.attentionMask.length, 64);
    assert.equal(enc.attentionMask.reduce((a, b) => a + b, 0), enc.tokens.filter((t) => t !== '[PAD]').length);
  });

  test('truncation reserves room for the special tokens', () => {
    const enc = tokenizer.encode(new Array(200).fill('word').join(' '));
    assert.equal(enc.truncated, true);
    assert.equal(enc.inputIds.length, 64);
    assert.equal(enc.tokens[0], '[CLS]');
    assert.equal(enc.tokens.at(-1), '[SEP]');
  });

  test('unknown words become [UNK] rather than throwing', () => {
    const enc = tokenizer.encode('\u{1F6A8}\u{1F6A8}\u{1F6A8}');
    assert.ok(enc.inputIds.length >= 2);
    assert.equal(enc.tokens[0], '[CLS]');
  });

  test('an absurdly long single word is [UNK], not a hang', () => {
    const enc = tokenizer.encode('a'.repeat(500));
    assert.ok(enc.tokens.includes('[UNK]'));
  });

  test('rejects a vocabulary missing its special tokens', () => {
    assert.throws(() => new WordPieceTokenizer(['hello', 'world']), /missing the/);
  });
});
